### ISSUE TITLE
Why is the gate oscillator low-pass filtered

### ISSUE THREAD

**Issue by vsariola** [hzdgopher/4klang#11]
Hi,

I'm wondering why is the gate oscillator low-pass filtered. Specifically, I'm referring to these [lines](https://github.com/hzdgopher/4klang/blob/e28554120325fcaaebbe8189eef16b57fd83f0a8/4klang_source/4klang.asm#L428). I rewrote the comments to understand what is happening:

```
fld     dword [WRK+go4kVCO_wrk.gatestate] ; g x, g is gatestate, x is the input to this filter 0/1
fsub    st1                               ; g-x x
fmul    dword [c_dc_const]                ; c(g-x) x
faddp   st1, st0                          ; x+c(g-x)
fst     dword [WRK+go4kVCO_wrk.gatestate] ; g'=x+c(g-x)
;
; Another way to look at this (remembering that c~0.996)  
; g'=cg+(1-c)x
; output g'
```
That is a low-pass filter / exponentially decaying moving average of x. I'm looking at the waveforms outputted by the gate and for sure they low-pass filtered versions of the input (gate bit).

Why generate an interesting gate signal and then filter all the interesting details away? Maybe gate was meant only for LFOs and this is to slightly smooth the signal?

Or maybe the point was to have a highpass filter i.e. to remove DC-offset? Then the code should return x-g' instead of g'.

**Comment by hzdgopher** [comment]
It is intended to be a lowpass filter to smooth the 0/1 ramp at the transition points.

Initially (hence the name) the gate mode was intended to be used as trance gate, so amplitude modulating arbitrary other signals (also the reason it produces 0/1 values instead of -1/1).
Without the "smoothing" you will get those nasty audible clicks in the resulting sound.

So that gate mode was never intended to be an actual audio generating mode, but rather another "LFO" variant. I kept it in for non LFO though, because why not :)

**Comment by vsariola** [comment]
Got it! So the LFO use-case assumption was valid.

As I am refactoring/rewriting everything inside the synth, I'll see if I let the gate live where it is, or should I have some kind of separate chopper/slicer effect with, for example, more straightforward beat syncing.

I'll probably also remove that filter. My gut feeling is that letting the audio guy add a separate low-pass filter to the gate/chopper/slicer only when it is really needed would save bytes, as the filter code doesn't have to be repeated. In any case, I prefer units to be as lean as possible, so the audio guy has the maximum flexibility. I suspect the gate is not so often used feature that winning/saving bytes here will be highly case dependent.

There's one problem leaving the low-pass filter for the audio guy: the current low-pass filter does not go very low. If you set its freq = 0, it filters everything away, but freq = 1 is quite already quite fast.  I encountered this when hacking together a compressor using the existing 4klang opcodes (it calculates the moving average signal level by squaring the signal and then low-pass filtering it with the slowest possible low pass filter (freq = 1); distorts it to calculate a gain for the signal in a nonlinear way). The compressor works, but freq = 1 still gives it a pretty fast response time. This could also be an issue for gate filtering.

**Comment by vsariola** [comment]
I will close this issue, as the gate is working as it is designed.
